### ISSUE TITLE
Ppm target error

### ISSUE THREAD

**Issue by kisanjong** [kisanjong/rotalabutterfly#14]
you cannot add a ppm target, at 0.1 0.5 ...

**Comment by kisanjong** [comment]
![2_zpskigt0t4c](https://cloud.githubusercontent.com/assets/12550864/9157015/e3fc64d8-3ee4-11e5-929a-28ba20875a9d.jpg)

**Comment by ravenwilde** [comment]
Oooooh, yeah, that's not good - I will add this to my list to fix

**Comment by ravenwilde** [comment]
I've set this and all other number fields to accept numbers to the .01 decimal place - you guys thing this is good enough?

**Comment by kisanjong** [comment]
Hi Jen 

I can't see why not, if it need changing I'm sure the users will request it :)

**Comment by kisanjong** [comment]
the text note: you can use numbers like "1/8", "1.25", "2,50", "3" will need changing to correspond with the 0.01 change as 1/8, 1/4 etc does not work but using 0.25 etc is working fine.
