### ISSUE TITLE
Site Structure

### ISSUE THREAD

**Issue by ravenwilde** [kisanjong/rotalabutterfly#2]
So.... wet's site had a number of different calculators, and I am just going to assume that (eventually) we'll want to recreate them all. We should probably figure out how we are going to structure the site and our files.... this would also be helpful while I am coding up the navigation.

So far we have:

*Nutrient Calculator
*Glossary
*Contact Form

What else is there and how do we want to structure the domain(s)?

**Comment by kisanjong** [comment]
Hi Jennifer most of wets stuff is on his github repo, ill explain them more later :)

i think having all the stuff running on rotalabutterfly.com, maybe in folders to seperate them but not full sub domains, the only sub domain will be yanc.rotalabutterfly.com that will host wets original calculator keeping it alive :)

for now the three navigations you mentioned are perfect :)

for static pages like contact and glossary a single file in the root should be ok?

Thanks

**Comment by ravenwilde** [comment]
Closing this for now - can be reopened if needed.
