### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by ravenwilde** [kisanjong/rotalabutterfly#3]
Making this an issue so I don't forget to do this. Also we should talk about its implementation.

Fabrizio - any preferences (from a back end standpoint) on how we handle this?

Jason - what was the library you suggested?

**Comment by kisanjong** [comment]
Jennifer this was the one i use on another site but im happy to use whatever you like as long as it sends me mail :)  a key captcha would be a bonus ;)

Thanks

**Comment by ravenwilde** [comment]
Which one?

**Comment by kisanjong** [comment]
https://www.google.com/recaptcha/intro/index.html

http://rotalabutterfly.com/contact.php / html is also good. :+1:

**Comment by fablau** [comment]
With the fact we are suing AJAX, I’d use that for the Contact From as well if you like. Just let me know the fields you’ll be passing to the backend, and I’ll write a simple PHP script to send out emails :)

**Comment by kisanjong** [comment]
Sounds good to me :)

Name
Email
Subject
Message

Captcha

Thanks :)

**Comment by ravenwilde** [comment]
Sure thing... going to make this a lower priority though. For now I'm focused on getting the nutrient calculator form done.

**Comment by kisanjong** [comment]
Jen ive added the contact form, hope you dont mind :) your more than welcome to change it if you like?

http://rotalabutterfly.com/test/contact-form.php

form tested on the test site works and im receiving the emails.

ive also added the header links for the form to existing page.. index . glossary etc

**Comment by ravenwilde** [comment]
Totally fine - looks great :)

**Comment by fablau** [comment]
Nice! Love it!

Good job Jen :)

Fab.

**Comment by ravenwilde** [comment]
Closing this issue out because its done - thanks Jason, nice work!
