### ISSUE TITLE
Glossary Page

### ISSUE THREAD

**Issue by ravenwilde** [kisanjong/rotalabutterfly#4]
Making this an issue so I don't forget to create this.

For now I'll just provide you with a plain html page and some sample markup... what url do you want this do eventually be located at and where should the file live? top level? or within its own directory?

**Comment by kisanjong** [comment]
http://rotalabutterfly.com/glossary.php / html is good. :+1: 

Thanks :)

**Comment by ravenwilde** [comment]
Jason - I merged my work into the dev branch again and it included a glossary.html for you to work on. I took what you had in glossary.txt and did some basic html markup around it to give it structure. I'll let you take it from here but if you need help making it look a certain way or whatever let me know.

 [Bootstrap documentation](http://getbootstrap.com/css/) should help you out with most markup/style related stuff.

**Comment by kisanjong** [comment]
Thanks Jennifer I'll take a look

**Comment by kisanjong** [comment]
glossary page updated to include links to the wiki pages for reference 

http://rotalabutterfly.com/test/glossary.html

**Comment by ravenwilde** [comment]
Closing this issue out because its done.
